add configuration file /etc/netscan for netscan add a function to check the existence of necessary commands in the system add gitignore file in root + minor changes

diff --git a/network/netscan b/network/netscan
--- a/network/netscan
+++ b/network/netscan
@@ -2,25 +2,18 @@
 #
 # scan networks and send ip, mac, interface manufacturer & possible hostname for units found
 #
-# Deploy:
-# cd $installation_path
-# cp netscan /usr/local/bin/ && chmod +x /usr/local/bin/netscan
-# cp netscan-logrotate /etc/logrotate.d/
-# cp netscan-cron /etc/cron.d/ && chmod +x /etc/cron.d/netscan-cron
-# systemctl restart cron.service
-#
 # Usage (run as root), arguments for each scan are quoted:
 # netscan "scan1" "scan2" ...
 # values for each scan are surrounded by braces:
 # "opt1='value1' opt2='value2' ..."
 #
 # Option values can be:
-# interface:	interface network name
-# ipsrange:		a range of ips in a CIDR format
-# ipsexclude:	list of ips separate by semicolon to exclude from scan
-# macsexclude:	list of mac adresses separate by semicolon to exclude from scan
-# filelog:		file where logs are sent
-# url:			URL of API to record data
+# interface:    interface network name
+# ipsrange:     a range of ips in a CIDR format
+# ipsexclude:   list of ips separate by semicolon to exclude from scan
+# macsexclude:  list of mac adresses separate by semicolon to exclude from scan
+# filelog:      file where logs are sent
+# url:          URL of API to record data
 #
 # Example:
 # netscan "interface='wlan0' ipsrange='192.168.0.1/24' ipsexclude='192.168.0.1,192.168.0.100,192.168.0.101,192.168.0.102' url='https://example.org/record.php' filelog='/var/log/netscan/netscan.log'"
@@ -28,30 +21,6 @@
 # default options:
 # see belows in DATA section
 
-
-#########  DATA
-
-#### Here is manual configuration:
-# uncomment and modify
-#
-interface_default="" # "wlan0"
-ipsrange_default="" # "192.168.0.0/24"
-url_default=""
-filelog_default="/var/log/netscan/$(basename $0).log"
-ipsexclude_default="" # "192.168.0.1,192.168.0.100,192.168.0.101"
-macsexclude_default="" # "b8:27:eb:48:ae:35"
-
-# Defines whether debug logs are written or not. "y" to write the debug log, null to not do so
-debug="y"
-
-#### Defines command paths
-# Change following values if necessary
-cmd_ip="/bin/ip"
-cmd_arpscan="/usr/sbin/arp-scan"
-cmd_nmap="nmap"
-cmd_nbtscan="nbtscan"
-cmd_jq="jq"
-cmd_curl="curl"
 
 #########  FUNCTION
 
@@ -67,8 +36,33 @@ _log_debug() {
 	return 0
 }
 
+# 1 list of commands to find
+_init_cmd() {
+	cmd_miss=
+	for cmd in ${1}; do
+		cmd_path=`whereis -b ${cmd} 2>/dev/null | sed -n "s|${cmd}: \([^ ]\+\).*|\1|p"`
+		if [ "${cmd_path}" ]; then
+			#eval "cmd_${cmd}=${cmd_path}"
+			eval "cmd_${cmd//-/}=${cmd_path}"
+		else
+			cmd_miss="${cmd_miss} ${cmd}"
+		fi
+	done
+	# exits if command is missing
+	if [ "${cmd_miss}" ]; then
+		_log "error - missing command(s): ${cmd_miss}"
+		echo -e "the following command(s) are missing, please install it:\n${cmd_miss}"
+		exit 1
+	fi
+}
+
 _init() {
 	eval "$*"
+
+	# get configuration file
+	file="/etc/netscan-etc"
+	! [ -f "$file" ] && echo "error - unable to find file: '$file'" && exit 1
+	source "$file"
 
 	# for ip version >= ss190107, with -j option
 	#interface_default="${interface_default:-$(${cmd_ip} -4 -j route show to default|${cmd_jq} -r '.[0].dev')}"
@@ -112,17 +106,7 @@ _init() {
 	path="$(dirname $filelog)"
 	! [ -d "$path" ] && mkdir -p "$path"
 
-	# exits if command is missing
-	miss_cmd=
-	for cmd in `compgen -v cmd_`; do
-		cmd="${!cmd}"
-		type $cmd 2>/dev/null 1>&2 || miss_cmd="${miss_cmd} ${cmd##*/}"
-	done
-	if [ "$miss_cmd" ]; then
-		_log "error - missing command(s): ${miss_cmd}"
-		echo -e "the following command(s) are missing, please install it:\n${miss_cmd}"
-		exit 1
-	fi
+	_init_cmd "ip arp-scan nmap nbtscan jq curl"
 }
 
 # Scan network with ARP
@@ -209,14 +193,6 @@ _add_data_nbt() {
 
 		[ "$hostname" ] && data=`${cmd_jq} -c "select(.ipv4 == \"${ip}\") |= . + {\"hostname\":\"${hostname,,}\"}"<<<"$data"`
 	done
-}
-
-# Generate a secure key to recording
-_key_gen() {
-	base=`date +%s`
-	key=`echo -n "${base:0:-2}" | sha256sum`
-	key=${key:5:20}
-	echo $key
 }
 
 # send json data to API for recording
